name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del código de la rama 'main'
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: '20' # Fuerza el uso de Node.js 20 para esta acción

      # Paso 2: Instalar las dependencias necesarias usando npm
      - name: Install dependencies
        run: npm install

      # Paso 3: Instalar la CLI de Railway desde el repositorio oficial
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Paso 4: Verificar que la CLI de Railway se instaló correctamente
      - name: Verify Railway CLI installation
        run: railway --version

      # Paso 5: Desplegar a Railway con reintentos en caso de fallos
      - name: Deploy to Railway with retries
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} # Usa el token de Railway almacenado en los secretos de GitHub
        run: |
          for i in {1..3}; do
            railway up && break
            echo "Retry $i failed, trying again..."
            sleep 10
          done
